apiVersion: v1
kind: Service
metadata:
  name: {{ include "crb.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crb.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "crb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crb.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crb.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "crb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
